import React from 'react'


const video_songs = () => {
  return (
    <div className='ml-[150px] flex align-middle justify-around flex-wrap m-3'>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/r6SbfF9FjTg?si=KtDn5tjnm6LACNdW" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/Wj8C_bpnkTY?si=f_9FAFURqWgEf137" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/z-diRlyLGzo?si=cQy-y-rGSHX967I4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/hgh0tcVQYpU?si=j_8uDcwBg-tzvbPR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/19nnjV93N0s?si=XleOzmgzdB95koov" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/0mQLTWvXbXM?si=SlB1OxR34LsVJjJJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/sK7riqg2mr4?si=m8pm-XEMA2c7OTMG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/9FXm9R2VTBg?si=w-EvLz3_jBM8QZZG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/z3UHfi9vpbc?si=pg-NBcT59sBOZ3xt" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/Umqb9KENgmk?si=ZMFeiYLwEmkfBRUu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/g0eO74UmRBs?si=P1os6dPyDmnGbwW6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/NY2gKc17YwI?si=_RmV0VxmldHNgKm9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/4tZhTmrlf8M?si=m2JjKkqtgYd5nxaJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/MAVzDNc-L4g?si=6gtKQrdoUOJmDmLC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/rWfxbAl82PE?si=rE3Vdk-DauHyjQB7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/__iWEwRYbL0?si=Z7gGQSN7Sz7VWjgH" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/AEIVhBS6baE?si=xuzzSxXwQaYEe_1S" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/o-Gmhk90JOE?si=p_qxtcnujvIAQVDS" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/ndtno2tBGbo?si=QKXQsbDzifobFTvz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/zWEOx7TSM6I?si=RThiVjxV--4tIfxl" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/H2f7MZaw3Yo?si=N1NZcPZfWOrrHYFg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/U3AfQsHvZVA?si=0Beo3ly7qQKhBZu-" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/UBBHpoW3AKA?si=yvBaL7VpgMCijmfU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/puKD3nkB1h4?si=rsETCj5vli_WmKsw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/m0wYJnCq-4M?si=Cp8v5AW5hiCuZ_Nl" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/bnqLzCsffwY?si=aMLo4qLSE3kU30BV" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/BKx_B1VZ2kw?si=RZsB_uoHoslvwH9R" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/PMXducIESQE?si=hXmqXritvlwXhP_0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/jMfvlh0tjyo?si=NOTOAAxZcQ0RkevJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/abiL84EAWSY?si=eiDY7WFrcLSDIRe9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/Ax0G_P2dSBw?si=pmK11l9l_zINx5Zf" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/9iIX4PBplAY?si=M1LkuQO-Vu2lxQLn" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/iii1NM-Zv1g?si=vDaJMPog_IWgyBVp" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/xutBFUf3LoU?si=vKJbmXOR5QCAXWpE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/d-uyxvQ7fb4?si=dy9xb6R5LAbO04Jv" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/LQmHKl3oNu0?si=VfhbRPTExwV5Ccgx" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>

    </div>

  )
}

export default video_songs
